# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# libraries need to be imported:
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox



class Ui_loginPage(object):
    def setupUi(self, loginPage):
        loginPage.setObjectName("loginPage")
        loginPage.resize(1054, 608)
        loginPage.setStyleSheet("QDialog{\n"
"background: white;\n"
"}\n"
"*{\n"
"font-family: sans-serif;\n"
"font-size: 24px;\n"
"}\n"
"QLabel{\n"
"font-family: oswald;\n"
"font-size: 35px;\n"
"font-style: bold;\n"
"}\n"
"QFrame{\n"
"background: #04374A;\n"
"border-radius: 15px\n"
"\n"
"}\n"
"#pushButton{\n"
"border: 0px;\n"
"background: none;\n"
"margin: 20px auto;\n"
"text-align: center;\n"
"border: 2px solid #2ecc71;\n"
"padding: 14px 50px;\n"
"outline: none;\n"
"color: white;\n"
"border-radius: 24px;\n"
"}\n"
"#pushButton:hover{\n"
"background-color: #2ecc71;\n"
"}\n"
"QToolButton{\n"
"border-radius: 60px;\n"
"background: transparent;\n"
"}\n"
"QLabel{\n"
"color: white;\n"
"}\n"
"QLineEdit{\n"
"border: 0px;\n"
"    background: transparent;\n"
"    margin: 20px auto;\n"
"    text-align: center;\n"
"    border: 2px solid #1abc9c;\n"
"    padding: 14px 10px;\n"
"    width: 200px;\n"
"    outline: none;\n"
"    color: white;\n"
"    border-radius: 24px;\n"
"}\n"
"QLineEdit:focus{\n"
"width: 280px;\n"
"    border-color: #2ecc71;\n"
"}\n"
"\n"
"#pushButton_2{\n"
"background: transparent;\n"
"color: #04374A;\n"
"font-family:  Oswald;\n"
"font-size: 20;\n"
"text-decoration: underline;\n"
"}\n"
"#pushButton_2:hover{\n"
"color: #1abc9c;\n"
"}")
        self.frame = QtWidgets.QFrame(loginPage)
        self.frame.setGeometry(QtCore.QRect(550, -10, 541, 631))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 190, 191, 61))
        font = QtGui.QFont()
        font.setFamily("oswald")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(150, 490, 251, 101))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")

        # we want to connect login function with this button
        self.pushButton.clicked.connect(self.login)

        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(100, 280, 351, 101))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 370, 351, 101))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(200, 30, 141, 141))
        self.toolButton.setStyleSheet("image:url(:/img/avatar2.svg)")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.widget = QtWidgets.QWidget(loginPage)
        self.widget.setGeometry(QtCore.QRect(170, 270, 461, 401))
        self.widget.setStyleSheet("image: url(:/img/boxes1.svg)")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(loginPage)
        self.label_2.setGeometry(QtCore.QRect(80, 170, 341, 91))
        self.label_2.setStyleSheet("background: white;\n"
"color: #04374A;\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(loginPage)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 260, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(-1)
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")

        # we want to open the sign up page when push button 2 is clicked and connect it
        self.pushButton_2.clicked.connect(self.openWindow1)

        self.label_3 = QtWidgets.QLabel(loginPage)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 341, 61))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(loginPage)
        QtCore.QMetaObject.connectSlotsByName(loginPage)

    def retranslateUi(self, loginPage):
        _translate = QtCore.QCoreApplication.translate
        loginPage.setWindowTitle(_translate("loginPage", "Dialog"))
        self.label.setText(_translate("loginPage", "LOGIN HERE !"))
        self.pushButton.setText(_translate("loginPage", "Login"))
        self.lineEdit.setPlaceholderText(_translate("loginPage", "username"))
        self.lineEdit_2.setPlaceholderText(_translate("loginPage", "password"))
        self.label_2.setText(_translate("loginPage", "Are you a new member ?"))
        self.pushButton_2.setText(_translate("loginPage", "Please sign-up first"))
        self.label_3.setText(_translate("loginPage", "INVENTORY SYSTEM"))

    # this is a constructor used while switching between windows:
    def __init__(self, window):
        self.window = window

    #this window opens the main page by closing the current page:
    def openWindow2(self):
        self.window.close()
        from mainPage import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(self.window)
        self.ui.setupUi(self.window)
        self.ui.name(self.lineEdit.text(),self.lineEdit_2.text())
        self.window.show()

    # this function opens the signup page by closing the current page:
    def openWindow1(self):
        self.window.close()
        from signup import Ui_Dialog
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog(self.window)
        self.ui.setupUi(self.window)
        #loginPage.hide()
        self.window.show()

    # this function is used to login user to the system by checking the user entries and finding the user form database:
    def login(self):
        conn = sqlite3.connect("inventory.bd")
        conn.execute('''CREATE TABLE IF NOT EXISTS users(
                                    id integer primary key AUTOINCREMENT,
                                    username text not null,
                                    email text not null unique,
                                    password text not null,
                                    age integer
                                    )''')
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()
        res = conn.execute("select * from users where username='%s' AND password='%s'" % (username,password))
        if len(res.fetchall())>0:
            QMessageBox.about(self.window, "Welcome!", "Welcome to the system")
            self.openWindow2()
        else:
            QMessageBox.about(self.window, "Warning!", "The user name or the password is wrong!")


import sources #imported sources for images

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginPage = QtWidgets.QDialog()
    ui = Ui_loginPage(loginPage)
    ui.setupUi(loginPage)
    loginPage.show()
    sys.exit(app.exec_())
