# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 545)
        MainWindow.setStyleSheet("QMainWindow{\n"
"backgorund: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 821, 601))
        self.frame.setStyleSheet("#frame{\n"
"background: white;\n"
"}\n"
"#label_2{\n"
"background: #04374A;\n"
"font-family: oswald;\n"
"font-size: 35px;\n"
"font-style: bold;\n"
"color: white;\n"
"border-radius: 20px;\n"
"}\n"
"#label{\n"
"color: #F8B400;\n"
"}\n"
"QPushButton{\n"
"border: 0px;\n"
"background: none;\n"
"margin: 20px auto;\n"
"text-align: center;\n"
"border: 2px solid #2ecc71;\n"
"padding: 14px 50px;\n"
"outline: none;\n"
"color: #2ecc71;;\n"
"border-radius: 24px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(46, 204, 113, 255), stop:1 rgba(142, 250, 99, 255));\n"
"color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(20, 300, 271, 251))
        self.widget.setStyleSheet("image: url(:/img/option.svg)")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 60, 381, 91))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(210, 140, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        # we have to connect to the openWindow1 method to change page to account window:
        self.pushButton.clicked.connect(self.openWindow)

        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 260, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        # we have to connect to the openWindow3 method to change page to product window:
        self.pushButton_2.clicked.connect(self.openWindow3)

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 681, 51))
        self.label_2.setStyleSheet("Qlabel{\n"
"backgorund: white;\n"
"font-family: oswald;\n"
"font-size: 35px;\n"
"font-style: bold;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 400, 141, 101))
        self.pushButton_3.setText("")

        # we have to connect to the openWindow2 method to change page to signup window:
        self.pushButton_3.clicked.connect(self.openWindow2)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icons8-sign-out-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 42))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.widget.raise_()
        self.label_2.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Account"))
        self.pushButton_2.setText(_translate("MainWindow", "Products"))
        self.label_2.setText(_translate("MainWindow", "Inventory system"))

    # constructor used for switching pages:
    def __init__(self, window):
        self.window = window

    # this function is used for passing the information from other pages or previous page:
    def name(self, name, password):
        self.label.setText("Welcome " + str(name) + "!")
        self.name = name
        self.password = password

    # open the account page
    def openWindow(self):
        self.window.close()
        from account import Ui_account
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_account(self.window)
        self.ui.setupUi(self.window)
        self.ui.name(self.name, self.password)
        self.window.show()

    # open product window:
    def openWindow3(self):
        self.window.close()
        from product import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow(self.window)
        self.ui.setupUi(self.window)
        self.ui.name(self.name, self.password)
        self.window.show()

    # opens signup window:
    def openWindow2(self):
        self.window.close()
        from signup import Ui_Dialog
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Dialog(self.window)
        self.ui.setupUi(self.window)
        self.window.show()


import sources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
