# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#libraries need to be imported:
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox




class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1058, 646)
        Dialog.setStyleSheet("QDialog{\n"
                             "background: white;\n"
                             "}\n"
                             "*{\n"
                             "font-family: sans-serif;\n"
                             "font-size: 24px;\n"
                             "}\n"
                             "QLabel{\n"
                             "font-family: oswald;\n"
                             "font-size: 35px;\n"
                             "font-style: bold;\n"
                             "}\n"
                             "#label{\n"
                             "font-size: 35px;\n"
                             "}\n"
                             "QFrame{\n"
                             "background: #04374A;\n"
                             "border-radius: 15px\n"
                             "\n"
                             "}\n"
                             "#pushButton{\n"
                             "border: 0px;\n"
                             "background: none;\n"
                             "margin: 20px auto;\n"
                             "text-align: center;\n"
                             "border: 2px solid #2ecc71;\n"
                             "padding: 14px 50px;\n"
                             "outline: none;\n"
                             "color: white;\n"
                             "border-radius: 24px;\n"
                             "}\n"
                             "#pushButton:hover{\n"
                             "background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(46, 204, 113, 255), stop:1 rgba(142, 250, 99, 255))\n"
                             "}\n"
                             "QToolButton{\n"
                             "border-radius: 60px;\n"
                             "background: transparent;\n"
                             "}\n"
                             "QLabel{\n"
                             "color: white;\n"
                             "}\n"
                             "QLineEdit{\n"
                             "border: 0px;\n"
                             "    background: transparent;\n"
                             "    margin: 20px auto;\n"
                             "    text-align: center;\n"
                             "    border: 2px solid #1abc9c;\n"
                             "    padding: 14px 10px;\n"
                             "    width: 200px;\n"
                             "    outline: none;\n"
                             "    color: white;\n"
                             "    border-radius: 24px;\n"
                             "}\n"
                             "QLineEdit:focus{\n"
                             "width: 280px;\n"
                             "    border-color: #2ecc71;\n"
                             "}\n"
                             "\n"
                             "#pushButton_2{\n"
                             "background: transparent;\n"
                             "color: #04374A;\n"
                             "font-family:  Oswald;\n"
                             "font-size: 20;\n"
                             "text-decoration: underline;\n"
                             "}\n"
                             "#pushButton_2:hover{\n"
                             "color: #1abc9c;\n"
                             "}")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(690, 140, 341, 91))
        self.label_2.setStyleSheet("background: white;\n"
                                   "color: #04374A;\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-10, -20, 541, 711))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 160, 221, 61))
        font = QtGui.QFont()
        font.setFamily("oswald")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(130, 550, 261, 101))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")

        # we have to connect the signup function to the button when it is clicked
        self.pushButton.clicked.connect(self.signup)

        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(90, 220, 351, 101))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 380, 351, 101))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(200, 30, 131, 131))
        self.toolButton.setStyleSheet("image:url(:/img/avatar3.svg)")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 300, 351, 101))
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 460, 351, 101))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(630, 50, 341, 61))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(460, 280, 461, 401))
        self.widget.setStyleSheet("image: url(:/img/boxes2.svg)")
        self.widget.setObjectName("widget")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 230, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(-1)
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")

        # we connect the function of opening login page window to pushbutton2
        self.pushButton_2.clicked.connect(self.openWindow)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Already a member ?"))
        self.label.setText(_translate("Dialog", "SIGN-UP HERE !"))
        self.pushButton.setText(_translate("Dialog", "Sign-up"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "username"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "password"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "e-mail"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "confirm password"))
        self.label_3.setText(_translate("Dialog", "INVENTORY SYSTEM"))
        self.pushButton_2.setText(_translate("Dialog", "Please login !"))

    # constructor used for switching between windows:
    def __init__(self, window):
        self.window = window

    # this functions open login page and closes the current page:
    def openWindow(self):
        self.window.close()
        from login import Ui_loginPage
        self.window = QtWidgets.QDialog()
        self.ui = Ui_loginPage(self.window)
        self.ui.setupUi(self.window)
        #Dialog.hide()
        self.window.show()

    # this function allow user to sign up to the system by inserting the user entries into the database
    def signup(self):
        conn = sqlite3.connect("inventory.bd")
        conn.execute('''CREATE TABLE IF NOT EXISTS users(
                            id integer primary key AUTOINCREMENT,
                            username text not null,
                            email text not null unique,
                            password text not null,
                            age integer
                            )''')

        username = self.lineEdit.text()
        email = self.lineEdit_3.text()
        password = self.lineEdit_2.text()
        confirm_pass = self.lineEdit_4.text()

        res = conn.execute("select * from users where email=?", (email,))
        #res = conn.execute("select * from users where email='%s'" % email) #The "%" operator is used to format a set of variables enclosed in a "tuple" (a fixed size list), together with a format string, which contains normal text together with "argument specifiers", special symbols like "%s" and "%d

        if username == "" or email == "" or password == "":
            QMessageBox.about(self.window,"warning","Please make sure that you have filled all the information")
            #QMessageBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        elif (len(res.fetchall())>0):
            QMessageBox.about(self.window, "warning", "The email that you have entered has already been used")
        elif password != confirm_pass:
            QMessageBox.about(self.window, "warning", "The password does not match!")
        else:
            conn.execute("insert into users(username,email,password) values(?, ?, ?)", (username, email, password))
            conn.commit()
            conn.close()
            QMessageBox.about(self.window,'welcome','Your account has been created successfully')
            self.openWindow()




import sources  # imported sources used for images

if __name__ == "__main__":
    import sys  # provides functions and variables that can manipulate the python running environment

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
