# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(387, 565)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 421, 621))
        self.frame.setStyleSheet("#frame{\n"
"background: white;\n"
"}\n"
"#frame_2{\n"
"background: #FAF5E4;\n"
"border-radius: 25px;\n"
"}\n"
"QLabel{\n"
"font-family: oswald;\n"
"font-size: 20px;\n"
"font-style: bold;\n"
"color: #04374A;\n"
"}\n"
"QLineEdit{\n"
"font-family: oswald;\n"
"font-size: 16px;\n"
"color: #F8B400;\n"
"border: 3px solid #E0DBCB;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton{\n"
"border: 0px;\n"
"background: none;\n"
"text-align: center;\n"
"border: 2px solid #04374A;\n"
"color: #04374A;\n"
"border-radius: 20px;\n"
"font-style: bold;\n"
"font-size: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #04374A;\n"
"color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 371, 41))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(50, 80, 321, 421))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 30, 160, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 101, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(72, 520, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        # we have to connect to the updating method to update information and change page to account window:
        self.pushButton.clicked.connect(self.updating)

        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(242, 520, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        # we have to connect to the openWindow method to change page to account window:
        self.pushButton_2.clicked.connect(self.openWindow)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Please enter new information for your account:"))
        self.label_2.setText(_translate("Dialog", "Name : "))
        self.label_3.setText(_translate("Dialog", "E-mail : "))
        self.label_4.setText(_translate("Dialog", "Password : "))
        self.label_5.setText(_translate("Dialog", "Age : "))
        self.pushButton.setText(_translate("Dialog", "Done"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))

    # constructor used for switching pages:
    def __init__(self, window):
        self.window = window

    # used for passing information from other pages:
    def name(self, name, password):
        self.name = name
        self.password = password

    # opens account page:
    def openWindow(self):
        self.window.close()
        from account import Ui_account
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_account(self.window)
        self.ui.setupUi(self.window)
        self.ui.name(self.name, self.password)
        self.window.show()

    # updates all the information entered by user from the database and opens account page:
    def updating(self):
        name = self.lineEdit_2.text()
        email = self.lineEdit.text()
        pass1 = self.lineEdit_4.text()
        age = self.lineEdit_3.text()
        conn = sqlite3.connect("inventory.bd")
        res = conn.execute("select * from users where email=?", (email,))
        if (len(res.fetchall()) > 0):
            QMessageBox.about(self.window, "warning", "The email address you have entered has already been used")
        else:
            if name != "":
                conn.execute("update users set username=? WHERE username=? AND password=?",
                             (name, self.name, self.password))
                conn.commit()
                self.name = name
            if email != "":
                conn.execute("update users set email=? WHERE username=? AND password=?",
                             (email, self.name, self.password))
                conn.commit()
            if pass1 != "":
                conn.execute("update users set password=? WHERE username=? AND password=?",
                             (pass1, self.name, self.password))
                conn.commit()
                self.password = pass1
            if age != "":
                conn.execute("update users set age=? WHERE username=? AND password=?",
                             (age, self.name, self.password))
                conn.commit()
            # conn.execute("update users set username=?, email=?, password=?, age=? WHERE username=? AND password=?",(name, email, pass1, age, self.name, self.password))
            # conn.commit()
            self.window.close()
            from account import Ui_account
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_account(self.window)
            self.ui.setupUi(self.window)
            self.ui.name(self.name, self.password)
            self.window.show()





import sources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(Dialog)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
